### ISSUE TITLE
Adonis 4 Compatibility

### ISSUE THREAD

**Issue by Spazer9** [nrempel/adonis-kue#11]
Is this integration compatible with version 4 of Adonis?

**Comment by danilopolani** [comment]
+1 @nrempel

**Comment by nrempel** [comment]
Hi all. No, it needs to be updated.

I've been swamped with other work lately.

I hope to update soon.

**Comment by enniel** [comment]
I added PR (#12) for this.

**Comment by nrempel** [comment]
Thank you!

Merged.

Will publish as `adonis-kue@4.0.0`. Please open new issues if anyone sees any errors!
