### ISSUE TITLE
Jobs generator

### ISSUE THREAD

**Issue by ahmadarif** [nrempel/adonis-kue#13]
Will the command be made to create the jobs template?

**Comment by nrempel** [comment]
There are currently no commands to generate a job template.

If you would like try to implement this and open a pull request, I would be happy to review and accept it. 🙂

**Comment by ahmadarif** [comment]
Hi, I made PR to fix this issue. Please review it :)

https://github.com/nrempel/adonis-kue/pull/18

**Comment by ahmadarif** [comment]
Hi, any updates on this? Thanks

**Comment by nrempel** [comment]
Thank you very much @ahmadarif!

I will release your patch in 5.0.0 👍🏻
