### ISSUE TITLE
Kue not running

### ISSUE THREAD

**Issue by haabnaseem** [nrempel/adonis-kue#14]
Hi, 
I have done the setup as in docs, but when i run kue:listen i get info: kue worker listening for 0 job(s)
in terminal, and nothing happens.

**Comment by nrempel** [comment]
Hi @haabnaseem, do you have job files in the `Jobs` directory?

See here for an example: https://github.com/nrempel/adonis-kue/tree/master/examples/app/Jobs

**Comment by haabnaseem** [comment]
@nrempel Yes, i copied example job file. 
and here is the code: 
```
  const data = { test: 'data' } // Data to be passed to job handle
const priority = 'normal' // Priority of job, can be low, normal, medium, high or critical
const attempts = 1 // Number of times to attempt job if it fails
const remove = false // Should jobs be automatically removed on completion
const job = kue.dispatch(Job.key, data, priority, attempts, remove)
const result = await job.result
```

I dont get any errors

**Comment by nrempel** [comment]
What does your directory structure look like? Jobs should be a directory sibling to Models and Controllers.

```tree
├── ace
├── app
│   ├── Commands
│   ├── Controllers
│   ├── Models
│   └── Jobs
│       ├── JobName.js
├── config
│   ├── app.js
│   ├── auth.js
│   ├── bodyParser.js
│   ├── cors.js
│   ├── database.js
│   ├── session.js
│   └── shield.js
├── database
├── package-lock.json
├── package.json
├── public
├── resources
├── server.js
├── start
│   ├── app.js
│   ├── kernel.js
│   └── routes.js
└── start.sh
```

**Comment by haabnaseem** [comment]
@nrempel Dir structure is same,

**Comment by nrempel** [comment]
I'm unable to reproduce this. If you can give me an example project that reproduces this problem, then I'll take a look.
