### ISSUE TITLE
Enqueue Job from Adonis Command

### ISSUE THREAD

**Issue by christiancannata** [nrempel/adonis-kue#19]
I'm trying to enqueue a Kue Job from a Command, but command doesn't terminate and it keeps running.

Do I have to do something inside the command to close the process from the job?

**Comment by nrempel** [comment]
The job command should automatically terminate once the `handle` function returns.

Can you share the code that is stuck?

**Comment by nrempel** [comment]
I'm closing this for now since I haven't heard back. But please re-open the issue you still have trouble.

**Comment by Hyra** [comment]
Late to the party, but i got the same behaviour:

My command handle looks like this:

```  async handle(args, options) {
    const data = {
      test: "something"
    };
    const priority = "medium";
    const attempts = 5;
    const remove = true;
    await kue.dispatch(Job.key, data, priority, attempts, remove).result;
    this.info("Job enqueue");
  }
```

It gets all the way to the "Job enqueue" info, but never exits.

When i remove the kue part then the command exits fine.
