### ISSUE TITLE
How to listen in linux with PM2?

### ISSUE THREAD

**Issue by wemersonrv** [nrempel/adonis-kue#26]
Hi. Congrats!!! Great package!!

How can i configure it to listen in a linux server with PM2 ?

**Comment by wemersonrv** [comment]
Hi. I am unable to go **production** because cannot automatically starts the jobs in PM2. What's wrong ?

If run `pm2 start adonis kue:listen` inside my project folder, it works... but if i try to use it automatically in a PM2 process file to make it automatic, not works.

**Comment by vigikaran** [comment]
https://github.com/ahmadarif/adonis4
Refer this, might helpfull

**Comment by MorenoMdz** [comment]
Thanks @vigikaran, I need something that allows me to run pm2 with `adonis kue:listen` as well if possible, the conf you passed may be a solution otherwise.

**Comment by ebnersilva** [comment]
Any updates on this?

**Comment by muscle-rhnkyr** [comment]
Did you guys try on app/kernel.js : 

```
const Kue = use('Kue');
Kue.listen();
```

**Comment by MaissonTi** [comment]
@ebnersilva use the command `pm2 start ./ace -- kue:listen`

**Comment by rhadamez** [comment]
The @muscle-rhnkyr ideia almost solved my problem, it only breaks my github actions. Don't know why.

The command `pm2 start ./ace -- kue:listen` return "[PM2][ERROR] Script not found" (I'm in the right folder). The solution works, but it breaks my CI, dont know why. Any solution?
