### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. How to fix ?

### ISSUE THREAD

**Issue by wemersonrv** [nrempel/adonis-kue#29]
It was working fine when has less than 4 jobs, but when put the 4th Job to works, the message above starts::

> (node:114256) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 job ttl exceeded listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by mauriciolucas22** [comment]
I @wemersonrv You fix this issue ?

**Comment by wemersonrv** [comment]
I don't know, i stop using adonis and its stuffs!
