### ISSUE TITLE
kue-dashboard

### ISSUE THREAD

**Issue by dspangenberg** [nrempel/adonis-kue#7]
Is there a possibility to view and manage the jobs with kue-dashboard?

**Comment by nrempel** [comment]
Hi, yes it should work the same as with just Kue.

Once, you start adonis-kue with the ace command, you can use the same process to connect to the user interface.

https://github.com/Automattic/kue#user-interface

Let me know if that helps!

**Comment by webdevian** [comment]
Thanks @nrempel! I have added an npm script to launch this for me (with [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) to get env vars)

```javascript
{
  "kue": "./ace kue:listen",
  "kue:inspect": "node_modules/kue/bin/kue-dashboard -p $(dotenv -p KUE_INSPECT_PORT) -r redis://$(dotenv -p REDIS_HOSTNAME):$(dotenv -p REDIS_PORT) -q prefix"
}
```

**Comment by dspangenberg** [comment]
Thanks, @nrempel. I tried this a few weeks ago, and kue-dashboard hasn't displayed any data. I will try it next week again.

**Comment by webdevian** [comment]
@dspangenberg It could be because adonis-kue removes jobs after they've completed, so they're just going straight through and you never see them in the interface.

Try queueing up some jobs before turning on the kue listener, then you should be able to see them in the kue queue interface, then when you turn the listener on it should process them and they'll be removed from kue

**Comment by nrempel** [comment]
This is true, I have it set to remove jobs after completion because I ran into issues with running out of memory.

I'm open to suggestions on how to handle this in a way that keeps the UI available.

**Comment by nrempel** [comment]
You should also now be able to set removeOnComplete to false so that they remain in the UI.

Just be aware that you can use up your memory if you are queueing a lot of messages.

https://github.com/nrempel/adonis-kue#dispatching-jobs
