### ISSUE TITLE
Start listening on main adonis start script

### ISSUE THREAD

**Issue by webdevian** [nrempel/adonis-kue#8]
Thank you for building this and introducing me to Kue! This could be very useful for a project I'm working on.

Is it possible to start the kue listener as part of the main server.js script? I can edit server.js and spawn a child process in there but this doesn't feel the most elegant solution.

**Comment by nrempel** [comment]
Hey there, thanks for checking it out!

adonis-kue is designed to be run in a separate process from the web server.

**Comment by webdevian** [comment]
In the end I just created an NPM script that runs both in separate node forever processes.
